/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tn_csdlpt;

import java.awt.Color;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.SQLException;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author zLittleMasterz
 */
public class RPDSKYTHIFORM extends javax.swing.JFrame {

    /**
     * Creates new form CHONNGAYRPDSKYTHI
     */
    private GIAOVIEN gvlogin;
    private String link1;
    public RPDSKYTHIFORM(GIAOVIEN gvlogin,String link1,String coSo) {
        initComponents();
        this.gvlogin = gvlogin;
        this.link1 = link1;
        System.out.println(link1);
        lblCoSo.setText(coSo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel9 = new javax.swing.JPanel();
        jLabel53 = new javax.swing.JLabel();
        bttThoat3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        bttInBaoCao = new javax.swing.JButton();
        dcTuNgay = new com.toedter.calendar.JDateChooser();
        dcDenNgay = new com.toedter.calendar.JDateChooser();
        lblCoSo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(750, 300));
        setUndecorated(true);

        jPanel9.setBackground(new java.awt.Color(252, 252, 252));
        jPanel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel9.setForeground(new java.awt.Color(0, 51, 204));

        jLabel53.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        jLabel53.setText("Từ ngày       :");
        jLabel53.setPreferredSize(new java.awt.Dimension(80, 40));

        bttThoat3.setBackground(new java.awt.Color(255, 83, 40));
        bttThoat3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(255, 102, 0), null, null));
        bttThoat3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bttThoat1MouseClicked(evt);
            }
        });

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TN/icon/icons8_delete_35px.png"))); // NOI18N

        javax.swing.GroupLayout bttThoat3Layout = new javax.swing.GroupLayout(bttThoat3);
        bttThoat3.setLayout(bttThoat3Layout);
        bttThoat3Layout.setHorizontalGroup(
            bttThoat3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bttThoat3Layout.createSequentialGroup()
                .addComponent(jLabel5)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        bttThoat3Layout.setVerticalGroup(
            bttThoat3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bttThoat3Layout.createSequentialGroup()
                .addComponent(jLabel5)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 153));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Báo cáo danh sách kỳ thi ");

        jLabel54.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        jLabel54.setText("Đến ngày     :");
        jLabel54.setPreferredSize(new java.awt.Dimension(80, 40));

        jSeparator1.setForeground(new java.awt.Color(0, 0, 153));

        bttInBaoCao.setBackground(new java.awt.Color(249, 231, 0));
        bttInBaoCao.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        bttInBaoCao.setForeground(new java.awt.Color(51, 51, 51));
        bttInBaoCao.setText("IN BÁO CÁO");
        bttInBaoCao.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bttInBaoCao.setContentAreaFilled(false);
        bttInBaoCao.setOpaque(true);
        bttInBaoCao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttInBaoCaoActionPerformed(evt);
            }
        });
        bttInBaoCao.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseEntered(MouseEvent e) {
                bttInBaoCao.setBackground(new Color(233, 217, 7));
            }

            @Override
            public void mouseExited(MouseEvent e) {
                bttInBaoCao.setBackground(new Color(249, 231, 0));
            }

            @Override
            public void mousePressed(MouseEvent e) {
                bttInBaoCao.setBackground(new Color(223, 208, 7));
            }

            @Override
            public void mouseReleased(MouseEvent e) {
                bttInBaoCao.setBackground(new Color(249, 231, 0));//To change body of generated methods, choose Tools | Templates.
            }
        });

        dcTuNgay.setDateFormatString("dd/MM/yyyy");
        dcTuNgay.setFont(new java.awt.Font("Tahoma", 0, 19)); // NOI18N
        dcTuNgay.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                dcTuNgayPropertyChange(evt);
            }
        });

        dcDenNgay.setDateFormatString("dd/MM/yyyy");
        dcDenNgay.setFont(new java.awt.Font("Tahoma", 0, 19)); // NOI18N

        lblCoSo.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        lblCoSo.setForeground(new java.awt.Color(0, 0, 153));
        lblCoSo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCoSo.setText("cơ sở 1");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(bttInBaoCao, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel53, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19)
                        .addComponent(dcTuNgay, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel54, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(dcDenNgay, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblCoSo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 394, Short.MAX_VALUE))
                .addGap(5, 5, 5)
                .addComponent(bttThoat3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bttThoat3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, 0)
                .addComponent(lblCoSo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 33, Short.MAX_VALUE)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel53, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dcTuNgay, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel54, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dcDenNgay, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(bttInBaoCao, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bttInBaoCaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttInBaoCaoActionPerformed
        Date tuNgay = dcTuNgay.getDate();
        Date denNgay = dcDenNgay.getDate();
        
        try {
            IODATA.xemReportDsKyThiTheoNgay(gvlogin.getTenLogin(), gvlogin.getMatKhau(), gvlogin.getCoSo(), tuNgay, denNgay,lblCoSo.getText(),link1);
            this.dispose();
        } catch (SQLException ex) {
            System.out.println("ERROR:"+ex.getMessage()+"RPDSKYTHIFORM.bttInBaoCaoActionPerformed()");
        }
    }//GEN-LAST:event_bttInBaoCaoActionPerformed

    private void bttThoat1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bttThoat1MouseClicked
        this.dispose();
    }//GEN-LAST:event_bttThoat1MouseClicked

    private void dcTuNgayPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_dcTuNgayPropertyChange
        try {
            dcDenNgay.setMinSelectableDate(dcTuNgay.getDate());
            if (dcDenNgay.getDate().before(dcTuNgay.getDate())) {
                dcDenNgay.setDate(dcDenNgay.getMinSelectableDate());
            }
        } catch (Exception e) {

        }
    }//GEN-LAST:event_dcTuNgayPropertyChange

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RPDSKYTHIFORM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RPDSKYTHIFORM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RPDSKYTHIFORM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RPDSKYTHIFORM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttInBaoCao;
    private javax.swing.JPanel bttThoat3;
    private com.toedter.calendar.JDateChooser dcDenNgay;
    private com.toedter.calendar.JDateChooser dcTuNgay;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblCoSo;
    // End of variables declaration//GEN-END:variables
}
