/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tn_csdlpt;

import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JSpinner;
import javax.swing.SpinnerDateModel;
import javax.swing.table.DefaultTableModel;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;
import org.jdesktop.swingx.autocomplete.ObjectToStringConverter;
import sun.java2d.pipe.SpanShapeRenderer;

/**
 *
 * @author zLittleMasterz
 */
public class SINHVIENFORM extends javax.swing.JFrame {

    /**
     * Creates new form MAINFORM
     */
    
    private Color mainBttColor = new Color(80,130,217);
    private SINHVIEN sinhvien;
    private ArrayList<KYTHI> dsKyThiDangDienRa;
    private ArrayList<KYTHI> dsKyThiSapToi = new ArrayList<>();
    private KYTHI ktsvChon;
    private SimpleDateFormat ngayFormat = new SimpleDateFormat("dd/MM/yyyy");
    private SimpleDateFormat gioFormat = new SimpleDateFormat("HH:mm a");
    private DefaultTableModel dftblDsKyThiDangDienRa = new DefaultTableModel();
    private DefaultTableModel dftblDsKyThiSapToi = new DefaultTableModel();
    private DefaultTableModel dftblBangDiem = new DefaultTableModel();
    private ArrayList<CAUHOICARD> dsCauHoi;
    private ArrayList<DIEMTHI> bangDiem;
    THOIGIAN dongHo;

    public SINHVIENFORM(SINHVIEN sinhvien) {
        initComponents();
        setStartPanelsColor();
        this.sinhvien = sinhvien;
        txtUserName.setText(this.sinhvien.getHoTen());
        dftblDsKyThiDangDienRa = (DefaultTableModel) tblKyThiSinhVien.getModel();
        dftblBangDiem = (DefaultTableModel) tblBangDiem.getModel();

        refreshPnlDsKyThi();
        refreshPnlHoSoSv();
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlGD_LamViec = new javax.swing.JPanel();
        MainBtt = new javax.swing.JPanel();
        bttUser = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtUserName = new javax.swing.JLabel();
        bttKyThi = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        unlKyThi = new javax.swing.JPanel();
        bttDiemThi = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        unlDiemThi = new javax.swing.JPanel();
        pnlKyThi = new javax.swing.JPanel();
        pnlKyThi.setVisible(false);
        pnlKyThiFunc = new javax.swing.JPanel();

        bttVaoThi = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblKyThiSinhVien = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        pnlDiemThi = new javax.swing.JPanel();
        pnlDiemThi.setVisible(false);
        pnlKyThiFunc1 = new javax.swing.JPanel();

        bttRpXemBT = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblBangDiem = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        pnlHoSoSv = new javax.swing.JPanel();
        pnlHoSoSv.setVisible(true);
        jPanel4 = new javax.swing.JPanel();
        jLabel81 = new javax.swing.JLabel();
        jLabel82 = new javax.swing.JLabel();
        jLabel83 = new javax.swing.JLabel();
        jLabel86 = new javax.swing.JLabel();
        jLabel87 = new javax.swing.JLabel();
        txtHo_HoSo = new javax.swing.JTextField();
        lblMaSv_HoSo = new javax.swing.JLabel();
        bttLuuHoSo = new javax.swing.JButton();
        bttSuaHoSo = new javax.swing.JButton();
        lblLop_HoSo = new javax.swing.JLabel();
        jLabel90 = new javax.swing.JLabel();
        txtTen_HoSo = new javax.swing.JTextField();
        jLabel91 = new javax.swing.JLabel();
        jLabel92 = new javax.swing.JLabel();
        lblKhoa_HoSo = new javax.swing.JLabel();
        dcNgaySinh_HoSo = new com.toedter.calendar.JDateChooser();
        txtDiaChi_HoSo = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel84 = new javax.swing.JLabel();
        jLabel85 = new javax.swing.JLabel();
        jLabel88 = new javax.swing.JLabel();
        bttXacNhanDoiMatKhau = new javax.swing.JButton();
        pwfMatKhauCu = new javax.swing.JPasswordField();
        pwfMatKhauMoi = new javax.swing.JPasswordField();
        pwfXacNhanMk = new javax.swing.JPasswordField();
        bttDoiMatKhau = new javax.swing.JButton();
        lblErrorMatKhauCu = new javax.swing.JLabel();
        lblErrorMatKhauMoi = new javax.swing.JLabel();
        lblErrorXnMatKhau = new javax.swing.JLabel();
        pnlThiTracNghiem = new javax.swing.JPanel();
        pnlThiTracNghiem.setVisible(false);
        pnlThongTinThiSinh = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        lblMonThi = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        lblThinhDoBaiThi = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        lblHoTenThiSinh = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        lblLopThiSinh = new javax.swing.JLabel();
        pnlThoiGian = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        lblTgConLai = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        pnlBaiThi = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        pnlLuaChon = new javax.swing.JPanel();
        bttNopBai = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1600, 900));
        setResizable(false);

        pnlGD_LamViec.setBackground(new java.awt.Color(255, 255, 255));
        pnlGD_LamViec.setPreferredSize(new java.awt.Dimension(1600, 900));
        pnlGD_LamViec.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        MainBtt.setBackground(new java.awt.Color(80, 130, 217));
        MainBtt.setPreferredSize(new java.awt.Dimension(1600, 132));

        bttUser.setBackground(new java.awt.Color(80, 130, 217));
        bttUser.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        bttUser.setForeground(new java.awt.Color(0, 0, 102));
        bttUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bttUserMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bttUserMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bttUserMousePressed(evt);
            }
        });
        bttUser.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TN/icon/userIcon.png"))); // NOI18N
        bttUser.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 90));

        txtUserName.setBackground(new java.awt.Color(253, 253, 253));
        txtUserName.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        txtUserName.setForeground(new java.awt.Color(249, 249, 249));
        txtUserName.setText("Nguyễn Nguyên Nguyên Nguyen ");
        bttUser.add(txtUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, -1, 34));

        bttKyThi.setBackground(new java.awt.Color(37, 74, 131));
        bttKyThi.setPreferredSize(new java.awt.Dimension(200, 100));
        bttKyThi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bttKyThiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bttKyThiMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bttKyThiMousePressed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 25)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Kỳ thi");

        unlKyThi.setBackground(new java.awt.Color(254, 240, 229));

        javax.swing.GroupLayout unlKyThiLayout = new javax.swing.GroupLayout(unlKyThi);
        unlKyThi.setLayout(unlKyThiLayout);
        unlKyThiLayout.setHorizontalGroup(
            unlKyThiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        unlKyThiLayout.setVerticalGroup(
            unlKyThiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout bttKyThiLayout = new javax.swing.GroupLayout(bttKyThi);
        bttKyThi.setLayout(bttKyThiLayout);
        bttKyThiLayout.setHorizontalGroup(
            bttKyThiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(unlKyThi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
        );
        bttKyThiLayout.setVerticalGroup(
            bttKyThiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bttKyThiLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(unlKyThi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        bttDiemThi.setBackground(new java.awt.Color(37, 74, 131));
        bttDiemThi.setPreferredSize(new java.awt.Dimension(200, 100));
        bttDiemThi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bttDiemThiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bttDiemThiMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bttDiemThiMousePressed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 25)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Điểm thi");

        unlDiemThi.setBackground(new java.awt.Color(254, 240, 229));

        javax.swing.GroupLayout unlDiemThiLayout = new javax.swing.GroupLayout(unlDiemThi);
        unlDiemThi.setLayout(unlDiemThiLayout);
        unlDiemThiLayout.setHorizontalGroup(
            unlDiemThiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        unlDiemThiLayout.setVerticalGroup(
            unlDiemThiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout bttDiemThiLayout = new javax.swing.GroupLayout(bttDiemThi);
        bttDiemThi.setLayout(bttDiemThiLayout);
        bttDiemThiLayout.setHorizontalGroup(
            bttDiemThiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(unlDiemThi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
        );
        bttDiemThiLayout.setVerticalGroup(
            bttDiemThiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bttDiemThiLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(unlDiemThi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout MainBttLayout = new javax.swing.GroupLayout(MainBtt);
        MainBtt.setLayout(MainBttLayout);
        MainBttLayout.setHorizontalGroup(
            MainBttLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainBttLayout.createSequentialGroup()
                .addComponent(bttUser, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(bttKyThi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(bttDiemThi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        MainBttLayout.setVerticalGroup(
            MainBttLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bttUser, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addComponent(bttKyThi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
            .addComponent(bttDiemThi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
        );

        pnlGD_LamViec.add(MainBtt, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1620, 90));

        pnlKyThiFunc.setBackground(new java.awt.Color(254, 254, 254));
        pnlKyThiFunc.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(254, 240, 229)));

        bttVaoThi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TN/icon/tracnghiemIcon.png"))); // NOI18N
        bttVaoThi.setText("Vào thi");
        bttVaoThi.setPreferredSize(new java.awt.Dimension(115, 37));
        bttVaoThi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttVaoThiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlKyThiFuncLayout = new javax.swing.GroupLayout(pnlKyThiFunc);
        pnlKyThiFunc.setLayout(pnlKyThiFuncLayout);
        pnlKyThiFuncLayout.setHorizontalGroup(
            pnlKyThiFuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlKyThiFuncLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bttVaoThi, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlKyThiFuncLayout.setVerticalGroup(
            pnlKyThiFuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlKyThiFuncLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bttVaoThi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        tblKyThiSinhVien.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        tblKyThiSinhVien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "MÃ MÔN HỌC", "MÔN THI", "LỚP", "LẦN", "NGÀY THI", "GIỜ BẮT ĐẦU", "SỐ CÂU", "THỜI GIAN", "TRẠNG THÁI"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblKyThiSinhVien.setRowHeight(35);
        tblKyThiSinhVien.setSelectionBackground(new java.awt.Color(181, 181, 181));
        tblKyThiSinhVien.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblKyThiSinhVien.getTableHeader().setReorderingAllowed(false);
        tblKyThiSinhVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblKyThiSinhVienMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblKyThiSinhVien);
        tblKyThiSinhVien.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (tblKyThiSinhVien.getColumnModel().getColumnCount() > 0) {
            tblKyThiSinhVien.getColumnModel().getColumn(0).setResizable(false);
            tblKyThiSinhVien.getColumnModel().getColumn(0).setPreferredWidth(70);
            tblKyThiSinhVien.getColumnModel().getColumn(1).setResizable(false);
            tblKyThiSinhVien.getColumnModel().getColumn(1).setPreferredWidth(120);
            tblKyThiSinhVien.getColumnModel().getColumn(2).setResizable(false);
            tblKyThiSinhVien.getColumnModel().getColumn(2).setPreferredWidth(60);
            tblKyThiSinhVien.getColumnModel().getColumn(3).setResizable(false);
            tblKyThiSinhVien.getColumnModel().getColumn(3).setPreferredWidth(5);
            tblKyThiSinhVien.getColumnModel().getColumn(4).setResizable(false);
            tblKyThiSinhVien.getColumnModel().getColumn(4).setPreferredWidth(80);
            tblKyThiSinhVien.getColumnModel().getColumn(5).setResizable(false);
            tblKyThiSinhVien.getColumnModel().getColumn(5).setPreferredWidth(25);
            tblKyThiSinhVien.getColumnModel().getColumn(6).setResizable(false);
            tblKyThiSinhVien.getColumnModel().getColumn(6).setPreferredWidth(10);
            tblKyThiSinhVien.getColumnModel().getColumn(7).setResizable(false);
            tblKyThiSinhVien.getColumnModel().getColumn(7).setPreferredWidth(15);
            tblKyThiSinhVien.getColumnModel().getColumn(8).setResizable(false);
            tblKyThiSinhVien.getColumnModel().getColumn(8).setPreferredWidth(40);
        }

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 153));
        jLabel2.setText("Danh sách kỳ thi của bạn");

        jSeparator2.setForeground(new java.awt.Color(0, 0, 153));

        javax.swing.GroupLayout pnlKyThiLayout = new javax.swing.GroupLayout(pnlKyThi);
        pnlKyThi.setLayout(pnlKyThiLayout);
        pnlKyThiLayout.setHorizontalGroup(
            pnlKyThiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlKyThiFunc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlKyThiLayout.createSequentialGroup()
                .addGroup(pnlKyThiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1371, Short.MAX_VALUE)
                    .addComponent(jSeparator2)
                    .addGroup(pnlKyThiLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 455, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 229, Short.MAX_VALUE))
        );
        pnlKyThiLayout.setVerticalGroup(
            pnlKyThiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlKyThiLayout.createSequentialGroup()
                .addComponent(pnlKyThiFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 646, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pnlGD_LamViec.add(pnlKyThi, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 1600, 810));

        pnlKyThiFunc1.setBackground(new java.awt.Color(254, 254, 254));
        pnlKyThiFunc1.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(254, 240, 229)));

        bttRpXemBT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TN/icon/icons8_business_report_35px.png"))); // NOI18N
        bttRpXemBT.setText("Xem lại bài thi");
        bttRpXemBT.setPreferredSize(new java.awt.Dimension(115, 37));
        bttRpXemBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttRpXemBTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlKyThiFunc1Layout = new javax.swing.GroupLayout(pnlKyThiFunc1);
        pnlKyThiFunc1.setLayout(pnlKyThiFunc1Layout);
        pnlKyThiFunc1Layout.setHorizontalGroup(
            pnlKyThiFunc1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlKyThiFunc1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bttRpXemBT, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlKyThiFunc1Layout.setVerticalGroup(
            pnlKyThiFunc1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlKyThiFunc1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bttRpXemBT, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                .addContainerGap())
        );

        tblBangDiem.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        tblBangDiem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "MÃ MÔN HOC", "TÊN MÔN HỌC", "LẦN", "NGÀY THI", "MÃ BT", "ĐIỂM"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblBangDiem.setRowHeight(35);
        tblBangDiem.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblBangDiem.getTableHeader().setReorderingAllowed(false);
        tblBangDiem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblBangDiemMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblBangDiem);
        if (tblBangDiem.getColumnModel().getColumnCount() > 0) {
            tblBangDiem.getColumnModel().getColumn(0).setResizable(false);
            tblBangDiem.getColumnModel().getColumn(0).setPreferredWidth(90);
            tblBangDiem.getColumnModel().getColumn(1).setResizable(false);
            tblBangDiem.getColumnModel().getColumn(1).setPreferredWidth(190);
            tblBangDiem.getColumnModel().getColumn(2).setResizable(false);
            tblBangDiem.getColumnModel().getColumn(2).setPreferredWidth(5);
            tblBangDiem.getColumnModel().getColumn(3).setResizable(false);
            tblBangDiem.getColumnModel().getColumn(3).setPreferredWidth(95);
            tblBangDiem.getColumnModel().getColumn(4).setResizable(false);
            tblBangDiem.getColumnModel().getColumn(4).setPreferredWidth(25);
            tblBangDiem.getColumnModel().getColumn(5).setResizable(false);
            tblBangDiem.getColumnModel().getColumn(5).setPreferredWidth(5);
        }

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 153));
        jLabel1.setText("Bảng điểm của bạn");

        jSeparator1.setForeground(new java.awt.Color(0, 0, 153));

        javax.swing.GroupLayout pnlDiemThiLayout = new javax.swing.GroupLayout(pnlDiemThi);
        pnlDiemThi.setLayout(pnlDiemThiLayout);
        pnlDiemThiLayout.setHorizontalGroup(
            pnlDiemThiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlKyThiFunc1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlDiemThiLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlDiemThiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlDiemThiLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabel1))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 1236, Short.MAX_VALUE)
                    .addComponent(jSeparator1))
                .addContainerGap(352, Short.MAX_VALUE))
        );
        pnlDiemThiLayout.setVerticalGroup(
            pnlDiemThiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDiemThiLayout.createSequentialGroup()
                .addComponent(pnlKyThiFunc1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 634, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pnlGD_LamViec.add(pnlDiemThi, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 1600, 810));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 153)), "Hồ sơ của bạn", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 24), new java.awt.Color(0, 0, 153))); // NOI18N

        jLabel81.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        jLabel81.setText("Họ               :");

        jLabel82.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        jLabel82.setText("Mã sinh viên:");

        jLabel83.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        jLabel83.setText("Thuộc khoa  :");

        jLabel86.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        jLabel86.setText("Lớp              :");

        jLabel87.setFont(new java.awt.Font("Tahoma", 2, 21)); // NOI18N
        jLabel87.setForeground(new java.awt.Color(0, 51, 204));
        jLabel87.setText("Thông tin cá nhân:");

        txtHo_HoSo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtHo_HoSo.setPreferredSize(new java.awt.Dimension(200, 35));
        txtHo_HoSo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtHo_HoSoMouseClicked(evt);
            }
        });
        txtHo_HoSo.setEnabled(false);

        lblMaSv_HoSo.setFont(new java.awt.Font("Tahoma", 0, 19)); // NOI18N
        lblMaSv_HoSo.setText("jLabel72");

        bttLuuHoSo.setBackground(new java.awt.Color(249, 231, 0));
        bttLuuHoSo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        bttLuuHoSo.setForeground(new java.awt.Color(51, 51, 51));
        bttLuuHoSo.setText("Lưu hồ sơ");
        bttLuuHoSo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bttLuuHoSo.setContentAreaFilled(false);
        bttLuuHoSo.setOpaque(true);
        bttLuuHoSo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttLuuHoSoActionPerformed(evt);
            }
        });
        bttLuuHoSo.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseEntered(MouseEvent e) {
                bttLuuHoSo.setBackground(new Color(233, 217, 7));
            }

            @Override
            public void mouseExited(MouseEvent e) {
                bttLuuHoSo.setBackground(new Color(249, 231, 0));
            }

            @Override
            public void mousePressed(MouseEvent e) {
                bttLuuHoSo.setBackground(new Color(223, 208, 7));
            }

            @Override
            public void mouseReleased(MouseEvent e) {
                bttLuuHoSo.setBackground(new Color(249, 231, 0));//To change body of generated methods, choose Tools | Templates.
            }
        });

        bttSuaHoSo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bttSuaHoSo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TN/icon/editRowIcon.png"))); // NOI18N
        bttSuaHoSo.setText("Chỉnh sửa hồ sơ");
        bttSuaHoSo.setPreferredSize(new java.awt.Dimension(79, 30));
        bttSuaHoSo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bttSuaHoSoMouseClicked(evt);
            }
        });

        lblLop_HoSo.setFont(new java.awt.Font("Tahoma", 0, 19)); // NOI18N
        lblLop_HoSo.setText("jLabel72");

        jLabel90.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        jLabel90.setText("Tên              :");

        txtTen_HoSo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtTen_HoSo.setPreferredSize(new java.awt.Dimension(200, 35));
        txtTen_HoSo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtTen_HoSoMouseClicked(evt);
            }
        });
        txtTen_HoSo.setEnabled(false);

        jLabel91.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        jLabel91.setText("Ngày sinh    :");

        jLabel92.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        jLabel92.setText("Địa chỉ        :");
        jLabel92.setPreferredSize(new java.awt.Dimension(126, 33));

        lblKhoa_HoSo.setFont(new java.awt.Font("Tahoma", 0, 19)); // NOI18N
        lblKhoa_HoSo.setText("jLabel72");

        dcNgaySinh_HoSo.setDateFormatString("dd/MM/yyyy");
        dcNgaySinh_HoSo.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N

        txtDiaChi_HoSo.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        txtDiaChi_HoSo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtDiaChi_HoSoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bttSuaHoSo, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabel87, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel92, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtDiaChi_HoSo))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel83, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel86, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel81, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel82, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel90, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel91, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtHo_HoSo, javax.swing.GroupLayout.DEFAULT_SIZE, 331, Short.MAX_VALUE)
                            .addComponent(txtTen_HoSo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblLop_HoSo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblKhoa_HoSo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(dcNgaySinh_HoSo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(bttLuuHoSo, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblMaSv_HoSo))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(123, 123, 123))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(bttSuaHoSo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(jLabel87)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel82, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMaSv_HoSo, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtHo_HoSo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel81, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel90, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTen_HoSo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel91, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dcNgaySinh_HoSo, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel92, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDiaChi_HoSo, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel86)
                    .addComponent(lblLop_HoSo, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel83, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblKhoa_HoSo, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addComponent(bttLuuHoSo, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 153)), "Mật khẩu", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 24), new java.awt.Color(0, 0, 153))); // NOI18N

        jLabel84.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        jLabel84.setText("Mật khẩu mới:");

        jLabel85.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        jLabel85.setText("Mật khẩu      :");

        jLabel88.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        jLabel88.setText("Xác nhận MK:");
        jLabel88.setPreferredSize(new java.awt.Dimension(137, 32));

        bttXacNhanDoiMatKhau.setBackground(new java.awt.Color(249, 231, 0));
        bttXacNhanDoiMatKhau.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        bttXacNhanDoiMatKhau.setForeground(new java.awt.Color(51, 51, 51));
        bttXacNhanDoiMatKhau.setText("Xác nhận đổi");
        bttXacNhanDoiMatKhau.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bttXacNhanDoiMatKhau.setContentAreaFilled(false);
        bttXacNhanDoiMatKhau.setOpaque(true);
        bttXacNhanDoiMatKhau.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bttXacNhanDoiMatKhauMouseClicked(evt);
            }
        });
        bttXacNhanDoiMatKhau.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseEntered(MouseEvent e) {
                bttXacNhanDoiMatKhau.setBackground(new Color(233, 217, 7));
            }

            @Override
            public void mouseExited(MouseEvent e) {
                bttXacNhanDoiMatKhau.setBackground(new Color(249, 231, 0));
            }

            @Override
            public void mousePressed(MouseEvent e) {
                bttXacNhanDoiMatKhau.setBackground(new Color(223, 208, 7));
            }

            @Override
            public void mouseReleased(MouseEvent e) {
                bttXacNhanDoiMatKhau.setBackground(new Color(249, 231, 0));//To change body of generated methods, choose Tools | Templates.
            }
        });

        pwfMatKhauCu.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        pwfMatKhauCu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pwfMatKhauCuMouseClicked(evt);
            }
        });

        pwfMatKhauMoi.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        pwfMatKhauMoi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pwfMatKhauMoiMouseClicked(evt);
            }
        });

        pwfXacNhanMk.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        pwfXacNhanMk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pwfXacNhanMkMouseClicked(evt);
            }
        });

        bttDoiMatKhau.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bttDoiMatKhau.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TN/icon/editRowIcon.png"))); // NOI18N
        bttDoiMatKhau.setText("Đổi mật khẩu");
        bttDoiMatKhau.setPreferredSize(new java.awt.Dimension(79, 30));
        bttDoiMatKhau.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bttDoiMatKhauMouseClicked(evt);
            }
        });

        lblErrorMatKhauCu.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lblErrorMatKhauCu.setForeground(new java.awt.Color(255, 0, 0));

        lblErrorMatKhauMoi.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lblErrorMatKhauMoi.setForeground(new java.awt.Color(255, 0, 0));

        lblErrorXnMatKhau.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lblErrorXnMatKhau.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bttDoiMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(151, 151, 151)
                                .addComponent(bttXacNhanDoiMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel88, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel85, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel84, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblErrorMatKhauCu, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(pwfMatKhauCu)
                                        .addComponent(pwfMatKhauMoi)
                                        .addComponent(pwfXacNhanMk, javax.swing.GroupLayout.DEFAULT_SIZE, 306, Short.MAX_VALUE))
                                    .addComponent(lblErrorMatKhauMoi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblErrorXnMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 32, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(bttDoiMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel85, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pwfMatKhauCu, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addComponent(lblErrorMatKhauCu, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel84, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pwfMatKhauMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addComponent(lblErrorMatKhauMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel88, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pwfXacNhanMk, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(lblErrorXnMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bttXacNhanDoiMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        javax.swing.GroupLayout pnlHoSoSvLayout = new javax.swing.GroupLayout(pnlHoSoSv);
        pnlHoSoSv.setLayout(pnlHoSoSvLayout);
        pnlHoSoSvLayout.setHorizontalGroup(
            pnlHoSoSvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHoSoSvLayout.createSequentialGroup()
                .addGap(148, 148, 148)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(119, Short.MAX_VALUE))
        );
        pnlHoSoSvLayout.setVerticalGroup(
            pnlHoSoSvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHoSoSvLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(pnlHoSoSvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        pnlGD_LamViec.add(pnlHoSoSv, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, -1, 740));

        pnlThiTracNghiem.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlThongTinThiSinh.setBackground(new java.awt.Color(255, 213, 132));
        pnlThongTinThiSinh.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 153), 2));
        pnlThongTinThiSinh.setPreferredSize(new java.awt.Dimension(1598, 140));

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(51, 0, 102));
        jLabel18.setText("Môn thi :");

        lblMonThi.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        lblMonThi.setForeground(new java.awt.Color(51, 0, 102));
        lblMonThi.setText("CSDL");

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(51, 0, 102));
        jLabel20.setText("Trình độ:");

        lblThinhDoBaiThi.setFont(new java.awt.Font("Tahoma", 1, 26)); // NOI18N
        lblThinhDoBaiThi.setForeground(new java.awt.Color(0, 153, 0));
        lblThinhDoBaiThi.setText("A");

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(51, 0, 102));
        jLabel22.setText("Họ tên:");

        lblHoTenThiSinh.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        lblHoTenThiSinh.setForeground(new java.awt.Color(51, 0, 102));
        lblHoTenThiSinh.setText("Nguyễn Nguyễn Nguyễn Nguyễn");

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(51, 0, 102));
        jLabel24.setText("Lớp    :");

        lblLopThiSinh.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        lblLopThiSinh.setForeground(new java.awt.Color(51, 0, 102));
        lblLopThiSinh.setText("D18CQCN01");

        pnlThoiGian.setBackground(new java.awt.Color(255, 255, 255));
        pnlThoiGian.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(127, 153, 255)));

        jLabel26.setFont(new java.awt.Font("Sitka Subheading", 1, 36)); // NOI18N
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TN/icon/timeIcon.png"))); // NOI18N
        jLabel26.setPreferredSize(new java.awt.Dimension(177, 100));

        lblTgConLai.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        lblTgConLai.setForeground(new java.awt.Color(255, 0, 0));
        lblTgConLai.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTgConLai.setText("30:00");
        lblTgConLai.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                lblTgConLaiPropertyChange(evt);
            }
        });

        javax.swing.GroupLayout pnlThoiGianLayout = new javax.swing.GroupLayout(pnlThoiGian);
        pnlThoiGian.setLayout(pnlThoiGianLayout);
        pnlThoiGianLayout.setHorizontalGroup(
            pnlThoiGianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlThoiGianLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(lblTgConLai, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlThoiGianLayout.setVerticalGroup(
            pnlThoiGianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(lblTgConLai, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnlThongTinThiSinhLayout = new javax.swing.GroupLayout(pnlThongTinThiSinh);
        pnlThongTinThiSinh.setLayout(pnlThongTinThiSinhLayout);
        pnlThongTinThiSinhLayout.setHorizontalGroup(
            pnlThongTinThiSinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlThongTinThiSinhLayout.createSequentialGroup()
                .addGap(142, 142, 142)
                .addGroup(pnlThongTinThiSinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlThongTinThiSinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblHoTenThiSinh)
                    .addComponent(lblLopThiSinh))
                .addGap(186, 186, 186)
                .addGroup(pnlThongTinThiSinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlThongTinThiSinhLayout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblThinhDoBaiThi))
                    .addGroup(pnlThongTinThiSinhLayout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblMonThi)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnlThoiGian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlThongTinThiSinhLayout.setVerticalGroup(
            pnlThongTinThiSinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlThongTinThiSinhLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(pnlThongTinThiSinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(lblMonThi)
                    .addComponent(jLabel22)
                    .addComponent(lblHoTenThiSinh))
                .addGap(18, 18, 18)
                .addGroup(pnlThongTinThiSinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlThongTinThiSinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel20)
                        .addComponent(lblThinhDoBaiThi))
                    .addGroup(pnlThongTinThiSinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel24)
                        .addComponent(lblLopThiSinh)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnlThongTinThiSinhLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlThoiGian, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlThiTracNghiem.add(pnlThongTinThiSinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jScrollPane1.setHorizontalScrollBar(null);
        jScrollPane1.getVerticalScrollBar().setUnitIncrement(16);

        pnlBaiThi.setBackground(new java.awt.Color(255, 255, 193));
        pnlBaiThi.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 0, 1, new java.awt.Color(0, 0, 102)));
        pnlBaiThi.setPreferredSize(new java.awt.Dimension(1220, 345));

        javax.swing.GroupLayout pnlBaiThiLayout = new javax.swing.GroupLayout(pnlBaiThi);
        pnlBaiThi.setLayout(pnlBaiThiLayout);
        pnlBaiThiLayout.setHorizontalGroup(
            pnlBaiThiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnlBaiThiLayout.setVerticalGroup(
            pnlBaiThiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(pnlBaiThi);
        pnlBaiThi.getAccessibleContext().setAccessibleParent(pnlBaiThi);

        pnlThiTracNghiem.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 1280, 740));

        jPanel1.setBackground(new java.awt.Color(255, 213, 132));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 153), 2));
        jPanel1.setPreferredSize(new java.awt.Dimension(318, 750));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlLuaChon.setOpaque(false);
        pnlLuaChon.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));
        jPanel1.add(pnlLuaChon, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 15, 290, 650));

        bttNopBai.setBackground(new java.awt.Color(0, 193, 142));
        bttNopBai.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        bttNopBai.setForeground(new java.awt.Color(255, 255, 255));
        bttNopBai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TN/icon/nopBaiIcon.png"))); // NOI18N
        bttNopBai.setText("TRẢ BÀI");
        bttNopBai.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bttNopBai.setContentAreaFilled(false);
        bttNopBai.setOpaque(true);
        bttNopBai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttNopBaiActionPerformed(evt);
            }
        });
        bttNopBai.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseEntered(MouseEvent e) {
                bttNopBai.setBackground(new Color(16, 212, 160));
            }

            @Override
            public void mouseExited(MouseEvent e) {
                bttNopBai.setBackground(new Color(0, 193, 142));
            }

            @Override
            public void mousePressed(MouseEvent e) {
                bttNopBai.setBackground(new Color(1, 155, 115));
            }

            @Override
            public void mouseReleased(MouseEvent e) {
                bttNopBai.setBackground(new Color(0, 193, 142));//To change body of generated methods, choose Tools | Templates.
            }

        });
        jPanel1.add(bttNopBai, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 670, 313, 79));

        pnlThiTracNghiem.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1280, 130, -1, -1));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 722, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 543, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlGD_LamViec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(pnlThiTracNghiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlGD_LamViec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(pnlThiTracNghiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bttDiemThiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bttDiemThiMouseEntered
        if (!pnlDiemThi.isVisible()) {
            unlDiemThi.setBackground(new Color(41, 83, 147));
            bttDiemThi.setBackground(new Color(41, 83, 147));
        }
    }//GEN-LAST:event_bttDiemThiMouseEntered

    private void bttDiemThiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bttDiemThiMouseExited
        if (!pnlDiemThi.isVisible()) {
            bttDiemThi.setBackground(mainBttColor);
            unlDiemThi.setBackground(mainBttColor);
        }
    }//GEN-LAST:event_bttDiemThiMouseExited

    private void bttDiemThiMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bttDiemThiMousePressed
        setBttColor(bttDiemThi, unlDiemThi,pnlDiemThi);
        resetMaintabColor(new JPanel[] {bttKyThi},
                new JPanel[] {unlKyThi},
                new JPanel[] {pnlKyThi,pnlHoSoSv});
        refreshPnlDiemThi();
    }//GEN-LAST:event_bttDiemThiMousePressed

    private void bttUserMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bttUserMouseEntered
        bttUser.setBackground(new Color(41, 83, 147));
        txtUserName.setForeground(new Color(240,240,240));
    }//GEN-LAST:event_bttUserMouseEntered

    private void bttUserMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bttUserMousePressed
        pnlHoSoSv.setVisible(true);
        resetMaintabColor(new JPanel[] {bttKyThi,bttDiemThi},
                new JPanel[] {unlKyThi,unlDiemThi},
                new JPanel[] {pnlKyThi,pnlDiemThi});
    }//GEN-LAST:event_bttUserMousePressed

    private void bttUserMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bttUserMouseExited
        bttUser.setBackground(new Color(80,130,217));
        txtUserName.setForeground(Color.white);
    }//GEN-LAST:event_bttUserMouseExited

    private void bttVaoThiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttVaoThiActionPerformed
        int row = tblKyThiSinhVien.getSelectedRow();
        
        String maMH = String.valueOf(dftblDsKyThiDangDienRa.getValueAt(row, 0));
        String maLop = String.valueOf(dftblDsKyThiDangDienRa.getValueAt(row, 2));
        int lan = Integer.parseInt(String.valueOf(dftblDsKyThiDangDienRa.getValueAt(row, 3)));
        ktsvChon = new KYTHI();
        for (KYTHI kythi : dsKyThiDangDienRa) {
            if (kythi.getMaMH()==maMH&&kythi.getMaLop()==maLop&&kythi.getLan()==lan) {
                ktsvChon = kythi;
            }
        }

        long kt = ktsvChon.getNgayThi().getTime() + (ktsvChon.getTg() * 60 * 1000);
        Date gioKetThuc = new Date();
        gioKetThuc.setTime(kt);
        if (gioKetThuc.before(new Date())) {
            JOptionPane.showMessageDialog(rootPane, "Đã hết giờ làm bài, bạn không thể vào thi nữa!", "KỲ THI ĐÃ KẾT THÚC", HEIGHT);
            refreshPnlDsKyThi();
            return;
        }
        if (ktsvChon.getNgayThi().after(new Date())) {
            JOptionPane.showMessageDialog(rootPane, "Chưa đến giờ vào thi ", "KỲ THI CHƯA BẮT ĐẦU", HEIGHT);
            refreshPnlDsKyThi();
            return;
        }
        
        int soPhut = ktsvChon.getTg();
        String trinhDo = ktsvChon.getTrinhDo();
        int soCau = ktsvChon.getSoCau();
        
                
        dsCauHoi = IODATA.getDeThi(SINHVIEN.getTenUser(), SINHVIEN.getMatKhau(), sinhvien.getCoSo(), maMH, trinhDo, soCau);
        pnlGD_LamViec.setVisible(false);
        pnlThiTracNghiem.setVisible(true);
        lblHoTenThiSinh.setText(sinhvien.getHoTen());
        lblLopThiSinh.setText(sinhvien.getMaLop());
        lblThinhDoBaiThi.setText(trinhDo);
        lblMonThi.setText(maMH);
        
        pnlBaiThi.setPreferredSize(new Dimension(pnlBaiThi.getPreferredSize().width, (pnlBaiThi.getPreferredSize().height*soCau)+1));
        
        for (int i = 0; i < soCau; i++) {
            dsCauHoi.get(i).setSize(dsCauHoi.get(i).getPreferredSize());
            dsCauHoi.get(i).setLocation(0, i*dsCauHoi.get(i).getSize().height);
            pnlBaiThi.add(dsCauHoi.get(i));
            dsCauHoi.get(i).setVisible(true);
            
            pnlLuaChon.add(dsCauHoi.get(i).getPnlIsChon());    
            dsCauHoi.get(i).getPnlIsChon().setVisible(true);
        }
        dongHo = new THOIGIAN(ktsvChon.getNgayThi(), soPhut, lblTgConLai);
        dongHo.start();
        ktsvChon.setNgayThi(new Date());
    }//GEN-LAST:event_bttVaoThiActionPerformed

    private void lblTgConLaiPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_lblTgConLaiPropertyChange
        if (lblTgConLai.getText().compareToIgnoreCase("00:00")==0) {
            System.out.println("het gio");
            nopBai();
        }
    }//GEN-LAST:event_lblTgConLaiPropertyChange

    private void bttKyThiMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bttKyThiMousePressed
        setBttColor(bttKyThi, unlKyThi,pnlKyThi);
        resetMaintabColor(new JPanel[] {bttDiemThi},
            new JPanel[] {unlDiemThi},
            new JPanel[] {pnlDiemThi,pnlHoSoSv});
        refreshPnlDsKyThi();
    }//GEN-LAST:event_bttKyThiMousePressed

    private void bttKyThiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bttKyThiMouseExited
        if (!pnlKyThi.isVisible()) {
            bttKyThi.setBackground(mainBttColor);
            unlKyThi.setBackground(mainBttColor);
        }
    }//GEN-LAST:event_bttKyThiMouseExited

    private void bttKyThiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bttKyThiMouseEntered
        if (!pnlKyThi.isVisible()) {
            unlKyThi.setBackground(new Color(41, 83, 147));
            bttKyThi.setBackground(new Color(41, 83, 147));
        }
    }//GEN-LAST:event_bttKyThiMouseEntered

    private void tblKyThiSinhVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblKyThiSinhVienMouseClicked
        enableFunc(new JButton[]{bttVaoThi});
    }//GEN-LAST:event_tblKyThiSinhVienMouseClicked

    private void tblBangDiemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblBangDiemMouseClicked
        enableFunc(new JButton[]{bttRpXemBT});
    }//GEN-LAST:event_tblBangDiemMouseClicked

    private void bttRpXemBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttRpXemBTActionPerformed
        int row = tblBangDiem.getSelectedRow();
        
        int maBt = Integer.parseInt(String.valueOf(tblBangDiem.getValueAt(row, 4)));
        String monThi = String.valueOf(tblBangDiem.getValueAt(row, 0))+", "+String.valueOf(tblBangDiem.getValueAt(row, 1));
        String ngayThi = String.valueOf(tblBangDiem.getValueAt(row, 3));
        double diem = Double.parseDouble(String.valueOf(tblBangDiem.getValueAt(row, 5)));
        int lan = Integer.parseInt(String.valueOf(tblBangDiem.getValueAt(row, 2)));
        try {
            IODATA.xemReportBaiThi(SINHVIEN.getTenUser(), SINHVIEN.getMatKhau(), sinhvien.getCoSo(),
                    maBt, sinhvien.getMaLop(), sinhvien.getHoTen(), monThi, ngayThi, diem, lan,"");
        } catch (SQLException ex) {
            System.out.println("ERROR:"+ex.getMessage()+"SINHVIENFORM.bttRpXemBTActionPerformed()");
        }
    }//GEN-LAST:event_bttRpXemBTActionPerformed

    private void txtHo_HoSoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtHo_HoSoMouseClicked
        if (txtHo_HoSo.getForeground() == Color.RED) {
            txtHo_HoSo.setText("");
            txtHo_HoSo.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_txtHo_HoSoMouseClicked

    private void bttLuuHoSoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttLuuHoSoActionPerformed

        boolean kt = true;
        String ho = txtHo_HoSo.getText();
        String ten = txtTen_HoSo.getText();
        String ngaySinh = IODATA.formatDate(dcNgaySinh_HoSo.getDate());
        String diaChi = txtDiaChi_HoSo.getText();
        
        if (ho.isEmpty()) {
            txtHo_HoSo.setText("* Họ không được phép trống");
            txtHo_HoSo.setForeground(Color.RED);
            kt=false;
        }
        if (ho.length()>40) {
            txtHo_HoSo.setText("* Độ dài họ không được quá 40 ký tự");
            txtHo_HoSo.setForeground(Color.RED);
            kt=false;
        }
        if (ten.isEmpty()) {
            txtTen_HoSo.setText("* Tên không được bỏ trống");
            txtTen_HoSo.setForeground(Color.RED);
            kt=false;
        }
        if (ten.length() >10) {
            txtTen_HoSo.setText("* Độ dài tên không được quá 10 ký tự");
            txtTen_HoSo.setForeground(Color.RED);
            kt=false;
        }
        if (diaChi.isEmpty()) {
            txtDiaChi_HoSo.setText("* Địa chỉ không được phép trống");
            txtDiaChi_HoSo.setForeground(Color.RED);
            kt=false;
        }
        if (diaChi.length()>40) {
            txtDiaChi_HoSo.setText("* Độ dài địa chỉ không được quá 40 ký tự");
            txtDiaChi_HoSo.setForeground(Color.RED);
            kt=false;
        }
        if (kt) {
            try {
                sinhvien.setHo(ho);
                sinhvien.setTen(ten);
                sinhvien.setHoTen(ho+" "+ten);
                sinhvien.setDiaChi(diaChi);
                sinhvien.setNgaySinh(ngaySinh);
                IODATA.suaSinhVien(SINHVIEN.getTenUser(), SINHVIEN.getMatKhau(), sinhvien.getCoSo(), sinhvien);
                sinhvien.layTtSinhVien();
                refreshPnlHoSoSv();
                JOptionPane.showMessageDialog(rootPane, "Hồ sơ của bạn đã được cập nhật", "Sửa hồ sơ thành công", JOptionPane.INFORMATION_MESSAGE);
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(rootPane, ex.getMessage(), "Sửa hồ sơ thất bại", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_bttLuuHoSoActionPerformed

    private void bttSuaHoSoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bttSuaHoSoMouseClicked
        lblMaSv_HoSo.setEnabled(true);
        txtHo_HoSo.setEnabled(true);
        txtTen_HoSo.setEnabled(true);
        txtDiaChi_HoSo.setEnabled(true);
        dcNgaySinh_HoSo.setEnabled(true);
        bttLuuHoSo.setVisible(true);
        bttSuaHoSo.setEnabled(false);
    }//GEN-LAST:event_bttSuaHoSoMouseClicked

    private void txtTen_HoSoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtTen_HoSoMouseClicked
        if (txtTen_HoSo.getForeground() == Color.RED) {
            txtTen_HoSo.setText("");
            txtTen_HoSo.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_txtTen_HoSoMouseClicked

    private void txtDiaChi_HoSoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtDiaChi_HoSoMouseClicked
        if (txtDiaChi_HoSo.getForeground() == Color.RED) {
            txtDiaChi_HoSo.setText("");
            txtDiaChi_HoSo.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_txtDiaChi_HoSoMouseClicked

    private void bttDoiMatKhauMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bttDoiMatKhauMouseClicked
        bttDoiMatKhau.setEnabled(false);
        pwfMatKhauCu.setText("");
        pwfXacNhanMk.setText("");
        pwfMatKhauMoi.setText("");
        
        pwfMatKhauCu.setEnabled(true);
        pwfMatKhauMoi.setEnabled(true);
        pwfXacNhanMk.setEnabled(true);
        bttXacNhanDoiMatKhau.setVisible(true);
    }//GEN-LAST:event_bttDoiMatKhauMouseClicked

    private void bttXacNhanDoiMatKhauMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bttXacNhanDoiMatKhauMouseClicked
        String matKhauCu = String.valueOf(pwfMatKhauCu.getPassword());
        String matKhauMoi = String.valueOf(pwfMatKhauMoi.getPassword());
        String xnMatKhau = String.valueOf(pwfXacNhanMk.getPassword());
        boolean kt = true;
        if (matKhauCu.compareTo(sinhvien.getMatKhauSV())!=0) {
            lblErrorMatKhauCu.setText("* Sai mật khẩu");
            kt=false;
        }
        if (matKhauMoi.isEmpty()) {
            lblErrorMatKhauMoi.setText("* Mật khẩu không được phép trống");
            kt=false;
        }
        if (matKhauMoi.compareTo(xnMatKhau)!=0) {
            lblErrorXnMatKhau.setText("* Mật khẩu không trùng khớp ");
            kt=false;
        }
        if (kt) {
             try {
                sinhvien.setMatKhauSV(matKhauMoi);
                IODATA.suaSinhVien(SINHVIEN.getTenUser(), SINHVIEN.getMatKhau(), sinhvien.getCoSo(), sinhvien);
                sinhvien.layTtSinhVien();
                refreshPnlHoSoSv();
                JOptionPane.showMessageDialog(rootPane, "Đã đổi mật khẩu", "Đổi mật khẩu thành công", JOptionPane.INFORMATION_MESSAGE);
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(rootPane, ex.getMessage(), "Đổi mật khẩu thất bại", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_bttXacNhanDoiMatKhauMouseClicked

    private void pwfMatKhauCuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pwfMatKhauCuMouseClicked
        lblErrorMatKhauCu.setText("");
    }//GEN-LAST:event_pwfMatKhauCuMouseClicked

    private void pwfMatKhauMoiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pwfMatKhauMoiMouseClicked
        lblErrorMatKhauMoi.setText("");
    }//GEN-LAST:event_pwfMatKhauMoiMouseClicked

    private void pwfXacNhanMkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pwfXacNhanMkMouseClicked
        lblErrorXnMatKhau.setText("");
    }//GEN-LAST:event_pwfXacNhanMkMouseClicked

    private void bttNopBaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttNopBaiActionPerformed
        nopBai();
    }//GEN-LAST:event_bttNopBaiActionPerformed
 
    /**
     * @param args the command line arguments
     */
    
    public void setStartPanelsColor(){
        bttKyThi.setBackground(mainBttColor);
        bttDiemThi.setBackground(mainBttColor);
        
        unlKyThi.setBackground(mainBttColor);
        unlDiemThi.setBackground(mainBttColor);
    }
    
    public void setBttColor(JPanel bttPanel, JPanel unlPanel,JPanel pnlJPanel){
        bttPanel.setBackground(new Color(37, 74, 131));
        bttPanel.setBorder(BorderFactory.createMatteBorder(2, 2, 0, 2, Color.black));
        unlPanel.setBackground(new Color(254,240,229));
        pnlJPanel.setVisible(true);
    }
    
     public void resetMaintabColor(JPanel[] bttPanel, JPanel[] unlPanel, JPanel[] pnlPanel){
        disableFunc(new JButton[]{bttVaoThi});
        for (JPanel jPanel : bttPanel) {
            jPanel.setBackground(mainBttColor);
            jPanel.setBorder(BorderFactory.createEmptyBorder());
        }
        for (JPanel jPanel : unlPanel) {
            jPanel.setBackground(mainBttColor);
        }
        for (JPanel jPanel : pnlPanel) {
             jPanel.setVisible(false);
        }
    }
    
     
    public void disableFunc(JPanel pnlFunc){
        for (Component cpn : pnlFunc.getComponents()) {
            cpn.setEnabled(false);
        }
    }
    
    public void disableFunc(JButton[] bttFunc) {
        for (JButton jButton : bttFunc) {
            jButton.setEnabled(false);
        }
    }
    
    public void enableFunc(JPanel pnlFunc){
        for (Component cpn : pnlFunc.getComponents()) {
            cpn.setEnabled(true);
        }
    }

    public void enableFunc(JButton[] bttFunc) {
        for (JButton jButton : bttFunc) {
            jButton.setEnabled(true);
        }
    }
    

    
    public void nopBai(){
        dongHo.stop(true);
        int tongSoCau = dsCauHoi.size();
        int soCauDung = 0;
        for (CAUHOICARD cauhoi : dsCauHoi) {
            if (cauhoi.isDung()) {
                soCauDung++;
            }
        }
        double diem = (double) Math.round(((double)soCauDung/tongSoCau)*100)/10;

        int maBt = IODATA.nopBaiThi(sinhvien, ktsvChon.getMaMH(), ktsvChon.getLan(), diem, ktsvChon.getNgayThi(), dsCauHoi);
        JOptionPane.showMessageDialog(rootPane, new HOANTHANHBAITHI(soCauDung, tongSoCau, diem), "HOÀN THÀNH BÀI THI", JOptionPane.PLAIN_MESSAGE);
        if (maBt != 0) {
            int choose = JOptionPane.showConfirmDialog(rootPane, "Bạn có muốn xem lại bài làm của mình", "XEM LẠI BÀI LÀM", JOptionPane.YES_NO_OPTION);
            if (choose == JOptionPane.YES_OPTION) {
                try {
                    IODATA.xemReportBaiThi(SINHVIEN.getTenUser(), SINHVIEN.getMatKhau(), sinhvien.getCoSo(),
                            maBt, sinhvien.getMaLop(), sinhvien.getHoTen(), lblMonThi.getText() + "," + ktsvChon.getTenMH(),
                            ngayFormat.format(new Date()),diem,ktsvChon.getLan(),"");
                } catch (SQLException ex) {
                    System.out.println("ERROR: Lỗi format date SINHVIENFORM.nopBai()" + ex.getMessage());
                }
            }
        }
        pnlBaiThi.removeAll();
        pnlBaiThi.setPreferredSize(new Dimension(pnlBaiThi.getPreferredSize().width, 345));
        pnlBaiThi.revalidate();
        pnlBaiThi.repaint();
        pnlLuaChon.removeAll();
        dsCauHoi.clear();
        pnlThiTracNghiem.setVisible(false);
        pnlGD_LamViec.setVisible(true);
        
        refreshPnlDsKyThi();
    }
    
    public void refreshPnlDsKyThi(){
        disableFunc(new JButton[]{bttVaoThi});

        dftblDsKyThiDangDienRa.setRowCount(0);
        dsKyThiDangDienRa = IODATA.getDsKythiDangDienRa(sinhvien.getCoSo(), sinhvien.getMaSV());
        for (KYTHI kythi : dsKyThiDangDienRa) {
            String tt;
            long kt = kythi.getNgayThi().getTime() + (kythi.getTg() * 60 * 1000);
            Date ketThuc = new Date();
            ketThuc.setTime(kt);
            if (kythi.getNgayThi().after(new Date())) {
                tt = "Sắp tới";
            } else if (ketThuc.before(new Date())) {
                tt = "Đã kết thúc";           
            }else tt = "Đang diễn ra";
            
            dftblDsKyThiDangDienRa.addRow(new Object[]{
                kythi.getMaMH(),
                kythi.getTenMH(),
                kythi.getMaLop(),
                kythi.getLan(),
                ngayFormat.format(kythi.getNgayThi()),
                gioFormat.format(kythi.getNgayThi()),
                kythi.getSoCau(),
                kythi.getTg()+"p",
                tt
            });
        }
        
    }
    
    public void refreshPnlDiemThi(){
        disableFunc(new JButton[]{bttRpXemBT});
        
        dftblBangDiem.setRowCount(0);
        bangDiem = IODATA.getBangDiemSv(sinhvien);
        for (DIEMTHI diemthi : bangDiem) {
            dftblBangDiem.addRow(new Object[]{
                diemthi.getMaMh(),
                diemthi.getTenMh(),
                diemthi.getLan(),
                diemthi.getNgayThi(),
                diemthi.getMaBt(),
                diemthi.getDiem()
            });
        }
    }
    
    public void refreshPnlHoSoSv(){
        
        lblMaSv_HoSo.setText(sinhvien.getMaSV());
        txtHo_HoSo.setText(sinhvien.getHo());
        txtTen_HoSo.setText(sinhvien.getTen());
        txtDiaChi_HoSo.setText(sinhvien.getDiaChi());
        dcNgaySinh_HoSo.setDate(IODATA.formatDate(sinhvien.getNgaySinh()));
        lblLop_HoSo.setText(sinhvien.getMaLop().trim()+" - "+sinhvien.getTenLop());
        lblKhoa_HoSo.setText(sinhvien.getKhoa().getMaKhoa().trim()+" - "+sinhvien.getKhoa().getTenKhoa().trim());
        
        lblMaSv_HoSo.setEnabled(false);
        txtHo_HoSo.setEnabled(false);
        txtTen_HoSo.setEnabled(false);
        txtDiaChi_HoSo.setEnabled(false);
        dcNgaySinh_HoSo.setEnabled(false);
        bttLuuHoSo.setVisible(false);
        txtUserName.setText(sinhvien.getHoTen());
        
        bttDoiMatKhau.setEnabled(true);
        pwfMatKhauCu.setText(sinhvien.getMatKhauSV());
        pwfXacNhanMk.setText("");
        pwfMatKhauMoi.setText("");
        
        pwfMatKhauCu.setEnabled(false);
        pwfMatKhauMoi.setEnabled(false);
        pwfXacNhanMk.setEnabled(false);
        bttXacNhanDoiMatKhau.setVisible(false);       
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel MainBtt;
    private javax.swing.JPanel bttDiemThi;
    private javax.swing.JButton bttDoiMatKhau;
    private javax.swing.JPanel bttKyThi;
    private javax.swing.JButton bttLuuHoSo;
    private javax.swing.JButton bttNopBai;
    private javax.swing.JButton bttRpXemBT;
    private javax.swing.JButton bttSuaHoSo;
    private javax.swing.JPanel bttUser;
    private javax.swing.JButton bttVaoThi;
    private javax.swing.JButton bttXacNhanDoiMatKhau;
    private com.toedter.calendar.JDateChooser dcNgaySinh_HoSo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel81;
    private javax.swing.JLabel jLabel82;
    private javax.swing.JLabel jLabel83;
    private javax.swing.JLabel jLabel84;
    private javax.swing.JLabel jLabel85;
    private javax.swing.JLabel jLabel86;
    private javax.swing.JLabel jLabel87;
    private javax.swing.JLabel jLabel88;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel90;
    private javax.swing.JLabel jLabel91;
    private javax.swing.JLabel jLabel92;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblErrorMatKhauCu;
    private javax.swing.JLabel lblErrorMatKhauMoi;
    private javax.swing.JLabel lblErrorXnMatKhau;
    private javax.swing.JLabel lblHoTenThiSinh;
    private javax.swing.JLabel lblKhoa_HoSo;
    private javax.swing.JLabel lblLopThiSinh;
    private javax.swing.JLabel lblLop_HoSo;
    private javax.swing.JLabel lblMaSv_HoSo;
    private javax.swing.JLabel lblMonThi;
    private javax.swing.JLabel lblTgConLai;
    private javax.swing.JLabel lblThinhDoBaiThi;
    private javax.swing.JPanel pnlBaiThi;
    private javax.swing.JPanel pnlDiemThi;
    private javax.swing.JPanel pnlGD_LamViec;
    private javax.swing.JPanel pnlHoSoSv;
    private javax.swing.JPanel pnlKyThi;
    private javax.swing.JPanel pnlKyThiFunc;
    private javax.swing.JPanel pnlKyThiFunc1;
    private javax.swing.JPanel pnlLuaChon;
    private javax.swing.JPanel pnlThiTracNghiem;
    private javax.swing.JPanel pnlThoiGian;
    private javax.swing.JPanel pnlThongTinThiSinh;
    private javax.swing.JPasswordField pwfMatKhauCu;
    private javax.swing.JPasswordField pwfMatKhauMoi;
    private javax.swing.JPasswordField pwfXacNhanMk;
    private javax.swing.JTable tblBangDiem;
    private javax.swing.JTable tblKyThiSinhVien;
    private javax.swing.JTextField txtDiaChi_HoSo;
    private javax.swing.JTextField txtHo_HoSo;
    private javax.swing.JTextField txtTen_HoSo;
    private javax.swing.JLabel txtUserName;
    private javax.swing.JPanel unlDiemThi;
    private javax.swing.JPanel unlKyThi;
    // End of variables declaration//GEN-END:variables
}
