/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tn_csdlpt;

import java.awt.Color;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author zLittleMasterz
 */
public class TAOTAIKHOAN extends javax.swing.JFrame {

    /**
     * Creates new form TAOTAIKHOAN
     */
    private GIAOVIEN gvlogin;
    private MAINFORM mainform;
    
    public TAOTAIKHOAN(MAINFORM mainform, GIAOVIEN gvLogin, String newMaGv) {
        initComponents();
        this.gvlogin = gvLogin;
        lblTenUser.setText(newMaGv);
        cbxQuyen.addItem(QUYEN.TRUONG);
        if (gvLogin.getRole().compareTo("COSO")==0) {
            cbxQuyen.addItem(QUYEN.COSO);
            cbxQuyen.addItem(QUYEN.GIANGVIEN);
        }
        this.mainform = mainform;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        bttThoat = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lblTenUser = new javax.swing.JLabel();
        txtTenLogin = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        txtXnPassword = new javax.swing.JPasswordField();
        lblLoiTenLogin = new javax.swing.JLabel();
        lblLoiPassword = new javax.swing.JLabel();
        lblLoiXnPassword = new javax.swing.JLabel();
        cbxQuyen = new javax.swing.JComboBox<>();
        jLabel55 = new javax.swing.JLabel();
        bttXacNhanThem = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(700, 200));
        setUndecorated(true);

        jPanel8.setBackground(new java.awt.Color(252, 252, 252));
        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel8.setForeground(new java.awt.Color(0, 51, 204));

        jLabel50.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        jLabel50.setText("Tên user       : ");

        jLabel51.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        jLabel51.setText("Tên login       :");

        bttThoat.setBackground(new java.awt.Color(255, 83, 40));
        bttThoat.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(255, 102, 0), null, null));
        bttThoat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bttThoatMouseClicked(evt);
            }
        });

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TN/icon/icons8_delete_35px.png"))); // NOI18N

        javax.swing.GroupLayout bttThoatLayout = new javax.swing.GroupLayout(bttThoat);
        bttThoat.setLayout(bttThoatLayout);
        bttThoatLayout.setHorizontalGroup(
            bttThoatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bttThoatLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        bttThoatLayout.setVerticalGroup(
            bttThoatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 153));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Tạo login");

        jLabel53.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        jLabel53.setText("Mật khẩu       :");

        jLabel54.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        jLabel54.setText("Xác nhận MK :");

        jSeparator1.setForeground(new java.awt.Color(0, 0, 153));

        lblTenUser.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblTenUser.setText("jLabel4");

        txtTenLogin.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtTenLogin.setPreferredSize(new java.awt.Dimension(200, 35));
        txtTenLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtTenLoginMouseClicked(evt);
            }
        });

        txtPassword.setPreferredSize(new java.awt.Dimension(126, 35));
        txtPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtPasswordMouseClicked(evt);
            }
        });

        txtXnPassword.setPreferredSize(new java.awt.Dimension(126, 35));
        txtXnPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtXnPasswordMouseClicked(evt);
            }
        });

        lblLoiTenLogin.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        lblLoiTenLogin.setForeground(new java.awt.Color(255, 0, 0));
        lblLoiTenLogin.setVisible(true);

        lblLoiPassword.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        lblLoiPassword.setForeground(new java.awt.Color(255, 0, 0));
        lblLoiPassword.setVisible(true);

        lblLoiXnPassword.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        lblLoiXnPassword.setForeground(new java.awt.Color(255, 0, 0));
        lblLoiXnPassword.setVisible(true);

        cbxQuyen.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cbxQuyen.setPreferredSize(new java.awt.Dimension(64, 35));

        jLabel55.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        jLabel55.setText("Quyền           :");

        bttXacNhanThem.setBackground(new java.awt.Color(249, 231, 0));
        bttXacNhanThem.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        bttXacNhanThem.setForeground(new java.awt.Color(51, 51, 51));
        bttXacNhanThem.setText("Xác nhận");
        bttXacNhanThem.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bttXacNhanThem.setContentAreaFilled(false);
        bttXacNhanThem.setOpaque(true);
        bttXacNhanThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttXacNhanThemActionPerformed(evt);
            }
        });
        bttXacNhanThem.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseEntered(MouseEvent e) {
                bttXacNhanThem.setBackground(new Color(233, 217, 7));
            }

            @Override
            public void mouseExited(MouseEvent e) {
                bttXacNhanThem.setBackground(new Color(249, 231, 0));
            }

            @Override
            public void mousePressed(MouseEvent e) {
                bttXacNhanThem.setBackground(new Color(223, 208, 7));
            }

            @Override
            public void mouseReleased(MouseEvent e) {
                bttXacNhanThem.setBackground(new Color(249, 231, 0));//To change body of generated methods, choose Tools | Templates.
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bttThoat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel55, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel53, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel50, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel51, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel54, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtTenLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblTenUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtPassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtXnPassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblLoiTenLogin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLoiPassword, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblLoiXnPassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbxQuyen, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(46, 46, 46))
            .addComponent(bttXacNhanThem, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator1)
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bttThoat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel50, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTenUser, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel51, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTenLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblLoiTenLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel53)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblLoiPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel54)
                    .addComponent(txtXnPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblLoiXnPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel55, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxQuyen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addComponent(bttXacNhanThem, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtTenLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtTenLoginMouseClicked
        lblLoiTenLogin.setText("");
    }//GEN-LAST:event_txtTenLoginMouseClicked

    private void bttThoatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bttThoatMouseClicked
        this.dispose();
        mainform.refreshPnlGiaoVien();
    }//GEN-LAST:event_bttThoatMouseClicked

    private void bttXacNhanThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttXacNhanThemActionPerformed
         
        String tenUser = lblTenUser.getText();
        String tenLogin = txtTenLogin.getText();
        String password = String.valueOf(txtPassword.getPassword());
        String xnPassword = String.valueOf(txtXnPassword.getPassword());
        String quyen = ((QUYEN) cbxQuyen.getSelectedItem()).getValue();
        
        boolean kt = true;
        if (tenLogin.isEmpty()) {
            lblLoiTenLogin.setText("Tên login không được trống");
            kt= false;
        }
        if (password.isEmpty()) {
            lblLoiPassword.setText("Mật khẩu không được trống");
            kt= false;
        }
        if (xnPassword.compareTo(password)!=0) {
            lblLoiXnPassword.setText("Mật khẩu xác nhận không trùng khớp");
            kt= false;
        }
        
        if (kt) {
            try {
                int rs = IODATA.taoTaiKhoan(gvlogin.getTenLogin(), gvlogin.getMatKhau(), gvlogin.getCoSo(), tenLogin, password, tenUser, quyen);
               
                if (rs == 0) {
                    JOptionPane.showMessageDialog(rootPane, "Đã tạo login " + tenLogin + ". \n"
                            + "Login này có thể đăng nhập từ bây giờ", "Tạo login thành công", JOptionPane.INFORMATION_MESSAGE);
                    this.dispose();
                    mainform.refreshPnlGiaoVien();
                }
                if (rs == 1) {
                    lblLoiTenLogin.setText("Tên login đã tồn tại");
                    lblLoiTenLogin.setVisible(true);
                }
                if (rs == 2) {
                    JOptionPane.showMessageDialog(rootPane, "Tên user " + tenUser + " đã tồn tại. \n"
                            + "Login của giáo viên này có lẽ đã được tạo trước, \n"
                            + "hãy kiểm tra lại và thử lại sau", "Tạo login thất bại", JOptionPane.ERROR_MESSAGE);
                    this.dispose();
                    mainform.refreshPnlGiaoVien();
                }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(rootPane, ex.getMessage(), "Tạo login thất bại", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_bttXacNhanThemActionPerformed

    private void txtPasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPasswordMouseClicked
        lblLoiPassword.setText("");
    }//GEN-LAST:event_txtPasswordMouseClicked

    private void txtXnPasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtXnPasswordMouseClicked
        lblLoiXnPassword.setText("");
    }//GEN-LAST:event_txtXnPasswordMouseClicked

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bttThoat;
    private javax.swing.JButton bttXacNhanThem;
    private javax.swing.JComboBox<QUYEN> cbxQuyen;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblLoiPassword;
    private javax.swing.JLabel lblLoiTenLogin;
    private javax.swing.JLabel lblLoiXnPassword;
    private javax.swing.JLabel lblTenUser;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtTenLogin;
    private javax.swing.JPasswordField txtXnPassword;
    // End of variables declaration//GEN-END:variables
}
